#!/bin/bash

set -e
set -u
set -o pipefail

function log {
    echo "[Autopilot] $1"
}

case "$1" in
    up)
        docker-compose up "${@:2}"
        ;;
    down)
        docker-compose down "${@:2}"
        ;;
    pull)
        docker-compose pull "${@:2}"
        ;;
    cli)
        docker-compose exec -e AUTOPILOT_CLI=true autopilot artisan "${@:2}"
        ;;
    *)
        docker-compose exec autopilot "$@"
esac