---
version: "3"

services:
  autopilot:
    image: ghcr.io/sitepilot/autopilot:${APP_DOCKER_TAG:-latest}
    restart: always
    ports:
      - "${APP_HTTP_PORT:-8080}:8080"
    volumes:
      - "autopilot:/home/runtime/public/storage"
      - "./.env:/home/runtime/public/.env"
      - "./runtime.yml:/opt/runtime/config/runtime.yml:ro"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  mysql:
    image: "docker.io/bitnami/mariadb:10.5"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD:-supersecret}"
      MARIADB_DATABASE: "${DB_DATABASE:-autopilot}"
      MARIADB_USER: "${DB_USERNAME:-autopilot}"
      MARIADB_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - "mysql:/bitnami/mariadb"
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 5s
      timeout: 5s
      retries: 6

  redis:
    image: "docker.io/bitnami/redis:6.2"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "redis:/bitnami/redis/data"

  phpmyadmin:
    image: "docker.io/bitnami/phpmyadmin:5"
    restart: always
    environment:
      DATABASE_HOST: mysql
      PHP_UPLOAD_MAX_FILESIZE: 2G
      PHPMYADMIN_ABSOLUTE_URI: "/svc/phpmyadmin/"

  mailhog:
    image: "mailhog/mailhog:latest"
    restart: always

volumes:
  autopilot:
    driver: local
  mysql:
    driver: local
  redis:
    driver: local
